feature/OC-196/standards-documentation
OpenCatalogi/web-app pull request #98
Opened 2022-09-22 13:02 UTC by RalkeyOfficial

2022-09-23 09:16 UTC, lencodes requested changes
Looks good @RalkeyOfficial!

Left some comments underneath.

2022-09-23 09:16 UTC, lencodes commented on pwa/src/templates/documentation/standardsDocumentation/StandardsDocumentationTemplate.tsx
> +        <LeadParagraph>De standaarden die gebruikt worden door Open Catalogi</LeadParagraph>
I suggest making this a bit larger of a text ~~and to link to https://forumstandaardisatie.nl/ within that text~~.

Maybe add a button underneath to the [forumstandaardisatie](https://forumstandaardisatie.nl/) _and_ a button linking to https://forumstandaardisatie.nl/open-standaarden/verplicht 

![image](https://user-images.githubusercontent.com/66552932/191928933-5993e926-bf44-43e8-8b1e-db9292df6379.png)

2022-09-23 09:16 UTC, lencodes commented on pwa/src/templates/documentation/standardsDocumentation/StandardsDocumentationTemplate.tsx
> +        <LeadParagraph>De standaarden die gebruikt worden door Open Catalogi</LeadParagraph>
![image](https://user-images.githubusercontent.com/66552932/191927719-a9874e78-9a62-46f4-ba80-ea0c71d64bb9.png)

2022-09-23 09:16 UTC, lencodes commented on pwa/src/templates/documentation/standardsDocumentation/StandardsDocumentationTemplate.module.css
> +  max-width: 1440px;
Above comment is still relevant for future expansions on the container element, however, I'd suggest this container to be the default width.

2022-09-23 09:16 UTC, lencodes commented on pwa/src/templates/documentation/standardsDocumentation/StandardsDocumentationTemplate.module.css
> +  max-width: 1440px;
We're still making this mistake within `ComponentTemplate`, might be a good idea to update it there.

2022-09-26 09:17 UTC, remko48 approved these changes

2022-09-26 09:23 UTC, merged