feature/OC-197/breadcrumbs
OpenCatalogi/web-app pull request #99
Opened 2022-09-23 12:27 UTC by RalkeyOfficial

Added breadcrumbs

2022-09-23 13:28 UTC, remko48 requested changes
Looks really good!

Left some small comments.

2022-09-23 13:28 UTC, remko48 commented on pwa/src/templates/breadcrumb/BreadcrumbTemplate.tsx
> +
Nice job of translating the breadcrumbs! 
There is an easier way of doing this:
```
  const translatedBreadcrumbs= crumbs.map((crumb: any) => ({
    ...crumb,
    crumbLabel: t(_.upperFirst(crumb.crumbLabel)),
  }));
```
This way you can have both functions in one.

2022-09-23 13:28 UTC, remko48 commented on pwa/src/pages/documentation/index.tsx
> +export default IndexPage;
Nice catch!
I did notice that it still breaks on the organization's page breadcrumb. I suggest doing the same redirect there as you did here.

2022-09-23 15:14 UTC, lencodes requested changes
I think it would be nice to have it look like this.

The background could be `--web-app-color-background-light`. Probably needs updates in component package.

![image](https://user-images.githubusercontent.com/66552932/191994403-f4efc252-5b78-4dfc-bd5c-3bcd42e48aa8.png)


Final note: I see that Documentatie > Over doesn't show "Documentatie" in the crumbs.

2022-09-27 11:45 UTC, lencodes approved these changes
Nice!

2022-09-27 11:47 UTC, merged